# Generated by Django 6.0.1 on 2026-02-16 04:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(default='KGTL-QCL-01', max_length=50)),
                ('revision_no', models.CharField(default='01', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('part_name', models.CharField(blank=True, max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('operation_name', models.CharField(blank=True, max_length=200)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('prepared_by', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspection_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('machine_no', models.CharField(blank=True, max_length=50)),
                ('time_type', models.CharField(choices=[('SETUP', 'Setup'), ('4HRS', '4 Hours'), ('LAST', 'Last')], max_length=10)),
                ('value_1', models.CharField(blank=True, max_length=50)),
                ('value_2', models.CharField(blank=True, max_length=50)),
                ('value_3', models.CharField(blank=True, max_length=50)),
                ('value_4', models.CharField(blank=True, max_length=50)),
                ('value_5', models.CharField(blank=True, max_length=50)),
                ('value_6', models.CharField(blank=True, max_length=50)),
                ('value_7', models.CharField(blank=True, max_length=50)),
                ('value_8', models.CharField(blank=True, max_length=50)),
                ('value_9', models.CharField(blank=True, max_length=50)),
                ('value_10', models.CharField(blank=True, max_length=50)),
                ('value_11', models.CharField(blank=True, max_length=50)),
                ('value_12', models.CharField(blank=True, max_length=50)),
                ('value_13', models.CharField(blank=True, max_length=50)),
                ('value_14', models.CharField(blank=True, max_length=50)),
                ('judgment', models.CharField(blank=True, max_length=50)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='inspectionform.inspectionreport')),
            ],
            options={
                'db_table': 'schedule_entries',
                'ordering': ['sr', 'time_type'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
                ('special_char', models.CharField(blank=True, max_length=100)),
                ('spec', models.CharField(blank=True, max_length=100)),
                ('tolerance', models.CharField(blank=True, max_length=50)),
                ('inst', models.CharField(blank=True, max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspectionform.inspectionreport')),
            ],
            options={
                'db_table': 'inspection_items',
                'ordering': ['sr_no'],
                'unique_together': {('report', 'sr_no')},
            },
        ),
    ]
