# Generated by Django 6.0.1 on 2026-02-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionreport',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='updated_at',
        ),
    ]
