# Generated by Django 6.0.1 on 2026-02-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inspectionreport',
            table='inspection_reports',
        ),
    ]
