# Generated by Django 6.0.1 on 2026-02-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionform', '0002_alter_inspectionreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='sr',
            field=models.IntegerField(default=1),
        ),
    ]
