# Generated by Django 6.0.1 on 2026-02-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionform', '0003_alter_scheduleentry_sr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ['sr', 'time_type', 'row_order']},
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='row_order',
            field=models.IntegerField(default=0),
        ),
    ]
