# Generated by Django 6.0.1 on 2026-02-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionform', '0004_alter_scheduleentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='slot_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='time_type',
            field=models.CharField(choices=[('SETUP', 'Setup'), ('2HRS', '2 Hours'), ('4HRS', '4 Hours'), ('LAST', 'Last')], max_length=10),
        ),
    ]
