# Generated by Django 6.0.1 on 2026-03-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionform', '0005_pdi_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdireport',
            name='operation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
